// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPyms9yOvs8yfmQUq5rRd1dlBK0CffQpc',
    appId: '1:126518056940:web:7d4430e2da5f57328792c9',
    messagingSenderId: '126518056940',
    projectId: 'dpdp-cb20e',
    authDomain: 'dpdp-cb20e.firebaseapp.com',
    storageBucket: 'dpdp-cb20e.firebasestorage.app',
    measurementId: 'G-D1TZY8EEP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd50OunQaS7qh7NLvEkK0YKj1XUv0HiL0',
    appId: '1:126518056940:android:4d1e1f0809b478048792c9',
    messagingSenderId: '126518056940',
    projectId: 'dpdp-cb20e',
    storageBucket: 'dpdp-cb20e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeTOJc0VTvXzR7in2THUhqi2W6z3RnhG4',
    appId: '1:126518056940:ios:41b7ecb0cd98b4c28792c9',
    messagingSenderId: '126518056940',
    projectId: 'dpdp-cb20e',
    storageBucket: 'dpdp-cb20e.firebasestorage.app',
    iosBundleId: 'com.example.kyrotics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeTOJc0VTvXzR7in2THUhqi2W6z3RnhG4',
    appId: '1:126518056940:ios:41b7ecb0cd98b4c28792c9',
    messagingSenderId: '126518056940',
    projectId: 'dpdp-cb20e',
    storageBucket: 'dpdp-cb20e.firebasestorage.app',
    iosBundleId: 'com.example.kyrotics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPyms9yOvs8yfmQUq5rRd1dlBK0CffQpc',
    appId: '1:126518056940:web:be4f843c14a0f2718792c9',
    messagingSenderId: '126518056940',
    projectId: 'dpdp-cb20e',
    authDomain: 'dpdp-cb20e.firebaseapp.com',
    storageBucket: 'dpdp-cb20e.firebasestorage.app',
    measurementId: 'G-1769P17WSE',
  );
}